name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies in sub-folders
      run: |
        for dir in $(find . -maxdepth 1 -type d); do
          if [ -f "$dir/package.json" ]; then
            echo "Installing dependencies in $dir"
            cd $dir
            npm install
            cd ..
          fi
        done
